/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Linking;

public class App {

    public static void main(String[] args) {
        LinkedList<String> newlist = new LinkedList();
        newlist.insert("Road");
        newlist.insert("bashar");
        newlist.insert("ahmad");
        newlist.insert("aws");
        newlist.includes("basha");
        newlist.toString();
    }
}
