/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Linking;

import org.junit.jupiter.api.Test;

import java.util.function.Supplier;

import static org.junit.jupiter.api.Assertions.*;

public class appListTest {
    @Test
    public void testEmptyLinkedList() {
        System.out.println("testing empty linked list");
        LinkedList list = new LinkedList();
        assertNull("testEmptyLinkedList should be empty.", (Supplier<String>) list.head);
        System.out.println("finished test");
    }
}