/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blogsMD;

import blogsMD.labe26.codeL26;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void test_Lab26() {
       codeL26 codeL26   = new codeL26();
        int[] numArr = new int[]{8,4,23,42,16,15};
        codeL26.insertionSort(numArr);
        for (int num: numArr)
        assertTrue(true, " something went wrong ");
    }
}



