/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTables;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void  SettingKeyValueBeingInDataT() {
        Hashtable<String> hashTable = new Hashtable<String>(1000);
        hashTable.add("Jordan", "Amman");

        assertTrue(hashTable.contains("Jordan"));

    }

    @Test
    void  SettingKeyValueBeingInDataF() {
        Hashtable<String> hashTable = new Hashtable<String>(1000);
        hashTable.add("Jordan", "Amman");

        assertFalse(hashTable.contains("Iraq"));

    }
    @Test
    void RetrievingKey() {
        Hashtable<String> hashTable = new Hashtable<String>(1000);
        hashTable.add("Jordan", "Amman");

        assertEquals( hashTable.get("Jordan"),"Amman");

    }

    @Test
    void returnsNullForAKeyThatDoesNotExist () {
        Hashtable<String> hashTable = new Hashtable<String>(1000);
        hashTable.add("Jordan", "Amman");

        assertNull(hashTable.get("syria"));

    }

    @Test
    void returnsAListOfAllUniqueKeysThatExist () {
        Hashtable<String> hashTable = new Hashtable<String>(1000);
        hashTable.add("Jordan", "Amman");
        hashTable.add("12", "hello");
        hashTable.add("34", "welcome");
        hashTable.add("56", "hi");
        assertEquals(hashTable.toString(),"Key 94 --> Value  hi\n" +
                "Key 302 --> Value  hello\n" +
                "Key 698 --> Value  welcome\n" +
                "Key 995 --> Value  Amman\n");

    }
    @Test
    void handleCollision  () {
        Hashtable<String> hashTable = new Hashtable<String>(1000);
        hashTable.add("Jordan", "Amman");
        hashTable.add("12", "hello");
        hashTable.add("34", "welcome");
        hashTable.add("34", "welcome");

        assertEquals(hashTable.toString(),"Key 302 --> Value  hello\n" +
                "Key 698 --> Value  welcome\n" +
                "Key 995 --> Value  Amman\n");

    }

    @Test
    void retrieveAValueFromBucketWithinTheHashtableThatHasCollision() {
        Hashtable<String> hashTable = new Hashtable<String>(1000);
        hashTable.add("Jordan", "Amman");
        hashTable.add("12", "hello");
        hashTable.add("34", "welcome");
        hashTable.add("34", "welcome");

        assertEquals(hashTable.get("34"),"welcome");

    }
}
